name: CI/CD to EC2 with Docker

on:
  push:
    branches:
      - main
jobs:
  build-and-deloy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
          
    - name: Extract version from pom.xml
      run: echo "VERSION=v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
    - name: Build Docker image with version tag
      run: |
         docker build -t ${{secrets.DOCKER_USERNAME}}/laptopshop:${{ env.VERSION }} .
         docker tag ${{ secrets.DOCKER_USERNAME }}/laptopshop:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/laptopshop:latest

    - name: Push image to Docker Hub
      run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/laptopshop:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/laptopshop:latest
    
    - name: Deloy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.EC2_HOST}}
        username: ${{secrets.EC2_USER}}}
        key: ${{secrets.EC2_KEY}}
        port: 22
        script: |
          docker pull ${{secrets.DOCKER_USERNAME}}/laptopshop:${{ env.VERSION }}
          docker stop laptopshop || true
          docker rm laptopshop || true
          dock run -d --name laptopshop --env-file .env -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/laptopshop:${{ env.VERSION }}
    
